services:
  empanalytics.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    container_name: sql2019
    hostname: sql2019
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "VeryStrong!Passw0rd"
      MSSQL_PI: Developer
    restart: unless-stopped